<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], [], []],
    'cart' => [[], ['_controller' => 'App\\Controller\\CartController::index'], [], [['text', '/cart']], [], [], []],
    'cart_add' => [['id'], ['_controller' => 'App\\Controller\\CartController::addCart'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/add']], [], [], []],
    'cart_remove' => [['id'], ['_controller' => 'App\\Controller\\CartController::remove'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/cart/remove']], [], [], []],
    'chekout' => [[], ['_controller' => 'App\\Controller\\CartController::checkout'], [], [['text', '/cart/chekout']], [], [], []],
    'checkout' => [[], ['_controller' => 'App\\Controller\\CheckoutController::payement'], [], [['text', '/checkout/payement']], [], [], []],
    'contact' => [[], ['_controller' => 'App\\Controller\\ContactController::index'], [], [['text', '/contact']], [], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'email' => [[], ['_controller' => 'App\\Controller\\HomeController::testEmail'], [], [['text', '/email']], [], [], []],
    'product_simple' => [['id'], ['_controller' => 'App\\Controller\\ProductSimpleController::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/product']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_forgot_password_request' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::request'], [], [['text', '/reset-password']], [], [], []],
    'app_check_email' => [[], ['_controller' => 'App\\Controller\\ResetPasswordController::checkEmail'], [], [['text', '/reset-password/check-email']], [], [], []],
    'app_reset_password' => [['token'], ['token' => null, '_controller' => 'App\\Controller\\ResetPasswordController::reset'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/reset-password/reset']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'shop' => [[], ['_controller' => 'App\\Controller\\ShopController::index'], [], [['text', '/shop']], [], [], []],
    'user_page' => [[], ['_controller' => 'App\\Controller\\UserPageController::index'], [], [['text', '/my-account']], [], [], []],
    'user_addAddress' => [[], ['_controller' => 'App\\Controller\\UserPageController::addAdress'], [], [['text', '/my-account/addAddress']], [], [], []],
    'remove_address' => [['id'], ['_controller' => 'App\\Controller\\UserPageController::removeAdd'], [], [['variable', '', '[^/]++', 'id', true], ['text', '/my-account/removeAddress']], [], [], []],
];
