<?php

namespace Container0vYklfJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Controller\\CartController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\CheckoutController::index' => ['privates', '.service_locator.ZSQY2CZ', 'get_ServiceLocator_ZSQY2CZService', true],
            'App\\Controller\\CheckoutController::payement' => ['privates', '.service_locator.ZSQY2CZ', 'get_ServiceLocator_ZSQY2CZService', true],
            'App\\Controller\\HomeController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\HomeController::testEmail' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ProductSimpleController::index' => ['privates', '.service_locator.N_Zcg_f', 'get_ServiceLocator_NZcgFService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController::request' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ResetPasswordController::reset' => ['privates', '.service_locator.qwilqiL', 'get_ServiceLocator_QwilqiLService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\ShopController::index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\UserPageController::addAdress' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserPageController::index' => ['privates', '.service_locator.XjuMoQH', 'get_ServiceLocator_XjuMoQHService', true],
            'App\\Controller\\UserPageController::removeAdd' => ['privates', '.service_locator.Y0xaAFF', 'get_ServiceLocator_Y0xaAFFService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => ['privates', '.service_locator.st3ASTR', 'get_ServiceLocator_St3ASTRService', true],
            'App\\Controller\\CartController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\CheckoutController:index' => ['privates', '.service_locator.ZSQY2CZ', 'get_ServiceLocator_ZSQY2CZService', true],
            'App\\Controller\\CheckoutController:payement' => ['privates', '.service_locator.ZSQY2CZ', 'get_ServiceLocator_ZSQY2CZService', true],
            'App\\Controller\\HomeController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\HomeController:testEmail' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ProductSimpleController:index' => ['privates', '.service_locator.N_Zcg_f', 'get_ServiceLocator_NZcgFService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\ResetPasswordController:request' => ['privates', '.service_locator.6E9xidT', 'get_ServiceLocator_6E9xidTService', true],
            'App\\Controller\\ResetPasswordController:reset' => ['privates', '.service_locator.qwilqiL', 'get_ServiceLocator_QwilqiLService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\ShopController:index' => ['privates', '.service_locator.0Fb1YCW', 'get_ServiceLocator_0Fb1YCWService', true],
            'App\\Controller\\UserPageController:addAdress' => ['privates', '.service_locator.aKM6MDa', 'get_ServiceLocator_AKM6MDaService', true],
            'App\\Controller\\UserPageController:index' => ['privates', '.service_locator.XjuMoQH', 'get_ServiceLocator_XjuMoQHService', true],
            'App\\Controller\\UserPageController:removeAdd' => ['privates', '.service_locator.Y0xaAFF', 'get_ServiceLocator_Y0xaAFFService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\Admin\\DashboardController::configureUserMenu' => '?',
            'App\\Controller\\CartController::index' => '?',
            'App\\Controller\\CheckoutController::index' => '?',
            'App\\Controller\\CheckoutController::payement' => '?',
            'App\\Controller\\HomeController::index' => '?',
            'App\\Controller\\HomeController::testEmail' => '?',
            'App\\Controller\\ProductSimpleController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\ResetPasswordController::request' => '?',
            'App\\Controller\\ResetPasswordController::reset' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\ShopController::index' => '?',
            'App\\Controller\\UserPageController::addAdress' => '?',
            'App\\Controller\\UserPageController::index' => '?',
            'App\\Controller\\UserPageController::removeAdd' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\Admin\\DashboardController:configureUserMenu' => '?',
            'App\\Controller\\CartController:index' => '?',
            'App\\Controller\\CheckoutController:index' => '?',
            'App\\Controller\\CheckoutController:payement' => '?',
            'App\\Controller\\HomeController:index' => '?',
            'App\\Controller\\HomeController:testEmail' => '?',
            'App\\Controller\\ProductSimpleController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\ResetPasswordController:request' => '?',
            'App\\Controller\\ResetPasswordController:reset' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\ShopController:index' => '?',
            'App\\Controller\\UserPageController:addAdress' => '?',
            'App\\Controller\\UserPageController:index' => '?',
            'App\\Controller\\UserPageController:removeAdd' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]));
    }
}
