<?php

namespace Container0vYklfJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductSimpleControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ProductSimpleController' shared autowired service.
     *
     * @return \App\Controller\ProductSimpleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\ProductSimpleController'] = $instance = new \App\Controller\ProductSimpleController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ProductSimpleController', $container));

        return $instance;
    }
}
