<?php

namespace ContainerU1zmBj4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserPageControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\UserPageController' shared autowired service.
     *
     * @return \App\Controller\UserPageController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\UserPageController'] = $instance = new \App\Controller\UserPageController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\UserPageController', $container));

        return $instance;
    }
}
