<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMmvpo9M\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMmvpo9M/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMmvpo9M.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMmvpo9M\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMmvpo9M\App_KernelDevDebugContainer([
    'container.build_hash' => 'Mmvpo9M',
    'container.build_id' => '176599f6',
    'container.build_time' => 1647188618,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMmvpo9M');
