<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRBTxUxF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRBTxUxF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRBTxUxF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRBTxUxF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRBTxUxF\App_KernelDevDebugContainer([
    'container.build_hash' => 'RBTxUxF',
    'container.build_id' => '55bf706b',
    'container.build_time' => 1647197503,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRBTxUxF');
